### ISSUE TITLE
DSCParser 1.3.0.3 is working on one machine, and isn't working on another

### ISSUE THREAD

**Issue by aslan-im** [microsoft/DSCParser#23]
Hello!
Running the same script on 2 machines, on 1st PC it is working normally, on the second isn't.
Could you please tell me what is the dependency?
1st machine:
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

2st:
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
As you can see, the PS Version is the same. 
I'm getting the DSC using this script block:
```powershell
$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f "", $AzureDevOpsPAT )))
    $RequestURl = "https://dev.azure.com/$OrganizationName/$ProjectName/_apis/git/repositories/$RepoName/items?path=$RepoFilePath&download=true&api-version=5.0"
    $Headers = @{Authorization = ("Basic {0}" -f $base64AuthInfo) }

    Write-Verbose "Trying to get the file from ADO"
    try {
        $RequestSplat = @{
            Uri         = $RequestURl
            Method      = "GET"
            ContentType = "application/text"
            Headers     = $Headers
            ErrorAction = "STOP"
        }

        $BlueprintContent = Invoke-RestMethod @RequestSplat
        $BlueprintParsedObject = ConvertTo-DSCObject -Content $BlueprintContent
        Write-Verbose "File has been downloaded successfully"
        return $BlueprintParsedObject
    }
    catch {
        Write-Error $_.Exception | Select-object *
        break
    }
```

On the first machine it returns DSC object, on the second returns nothing

Downloaded files also can't be parsed on the second PC

**Comment by PrzemyslawKlys** [comment]
MAke sure you have the dsc module installed and version matches. If your dsc defines "use this module of this version" and you dont have it, dscparser will fail.

**Comment by PrzemyslawKlys** [comment]
Your DSC ps1 file has something like this:

![image](https://user-images.githubusercontent.com/15063294/156589258-b86619b2-0de7-4b1b-b9ae-3d533e3a103c.png)

Since it defines the exact module - this is why it doesn't work, because it expects a specific version. You have two choices. Install exactly what your DSC wants, or remove -ModuleVersion from your DSC file.

**Comment by aslan-im** [comment]
> Your DSC ps1 file has something like this:
> 
> ![image](https://user-images.githubusercontent.com/15063294/156589258-b86619b2-0de7-4b1b-b9ae-3d533e3a103c.png)
> 
> Since it defines the exact module - this is why it doesn't work, because it expects a specific version. You have two choices. Install exactly what your DSC wants, or remove -ModuleVersion from your DSC file.

Thank you for your help!
