### ISSUE TITLE
Not handling nested properties for AADAuthenticationMethodPolicyAuthenticator

### ISSUE THREAD

**Issue by jadamones** [microsoft/DSCParser#47]
DSCParser doesn't seem to properly handle the nested properties of the AAD Auth Method policies. I also noticed that diffs don't appear in delta reports for these resources.

**Comment by Kierow** [comment]
It's necessary to perform a `winrm quickconfig` in order to solve your issue.
For more information, you can refer to https://github.com/microsoft/Microsoft365DSC/issues/5064
